port: 8082

rpc:
  address: "127.0.0.1"
  port: 8081

registry:
  address: "127.0.0.1"
  port: 9090
  serverName: "Test"
config:
  serverName: "Test"
  address: "127.0.0.1"
  port: 9090
  config:
    - "mybatis"

